### ISSUE TITLE
Backport for PHP 5.6?

### ISSUE THREAD

**Issue by Bavragor** [spatie/typed#21]
What do you think about a backport for PHP 5.6?

**Comment by brendt** [comment]
At Spatie, we always push to keep our packages up to date with the latest PHP version. We strongly believe that in doing so, we can help the community grow towards an always up-to-date PHP stack.

Especially because how much this package relies on type hints, I don't think it would be a good idea to support 5.6 or 7.0. You're of course free to make a fork and support it yourself, it is definitely possible; but we generally don't want this kind of legacy support.
